name: Build and Deploy Maven Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to apply (e.g. v0.0.1)'
        required: false
  # push:
  #   branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: circuitpython-question

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: circuitpython-question/package-lock.json

      - name: Install dependencies and build
        working-directory: circuitpython-question
        run: |
          npm ci
          npm run build

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and deploy JAR
        run: mvn --batch-mode clean deploy -DskipTests -Drevision=${{ github.event.inputs.version || '0.0.1-SNAPSHOT' }}

      - name: Create Git tag
        if: ${{ github.event.inputs.version }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
